ci: improve the integration test of version command

diff --git a/.github/workflows/wc-integration-test.yaml b/.github/workflows/wc-integration-test.yaml
--- a/.github/workflows/wc-integration-test.yaml
+++ b/.github/workflows/wc-integration-test.yaml
@@ -26,7 +26,12 @@ jobs:
       - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
       - run: aqua policy allow
 
-      - run: aqua version
+      - run: |
+          version=$(aqua version)
+          if [ "$version" = unknown ]; then
+            echo "::error:: aqua version is unknown"
+            exit 1
+          fi
       - run: aqua version -j
       - run: aqua -v
       - run: aqua --help
